/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_COM_COMMAPI_TEST_I_WEATHER_SERVICE_SOMEIP_STUB_ADAPTER_HPP_
#define V0_COM_COMMAPI_TEST_I_WEATHER_SERVICE_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/com/commapi/test/IWeatherServiceStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace com {
namespace commapi {
namespace test {

template <typename _Stub = ::v0::com::commapi::test::IWeatherServiceStub, typename... _Stubs>
class IWeatherServiceSomeIPStubAdapterInternal
    : public virtual IWeatherServiceStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< IWeatherServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> IWeatherServiceSomeIPStubAdapterHelper;

    ~IWeatherServiceSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        IWeatherServiceSomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::com::commapi::test::IWeatherServiceStub,
        CommonAPI::Version
    > getIWeatherServiceInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::com::commapi::test::IWeatherServiceStub,
        std::tuple< >,
        std::tuple< int32_t>,
        std::tuple< >,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>>
    > getTempStubDispatcher;
    
    IWeatherServiceSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        IWeatherServiceSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< IWeatherServiceStub>(_stub)),
        getIWeatherServiceInterfaceVersionStubDispatcher(&IWeatherServiceStub::lockInterfaceVersionAttribute, &IWeatherServiceStub::getInterfaceVersion, false, true),
        getTempStubDispatcher(
            &IWeatherServiceStub::getTemp,
            false,
            _stub->hasElement(0),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)))
        
    {
        IWeatherServiceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1) }, &getTempStubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void IWeatherServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void IWeatherServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v0::com::commapi::test::IWeatherServiceStub, typename... _Stubs>
class IWeatherServiceSomeIPStubAdapter
    : public IWeatherServiceSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    IWeatherServiceSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          IWeatherServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace test
} // namespace commapi
} // namespace com
} // namespace v0

#endif // V0_COM_COMMAPI_TEST_I_Weather_Service_SOMEIP_STUB_ADAPTER_HPP_
